### PR TITLE
Rearrange TOC

### PR DESCRIPTION
**Pull request by gjtorikian**
This PR changes some of the doc arrangement a bit:

* It pulls the Glossary out into its own top-level navigation piece
* It seems to divvy up the existing "Developer Overview" into three parts:
   * one breaking down the components of an SDM
   * one describing broadly how to develop against an SDM (debugging, logging, events to listen to)
   * a final part to talk about "SDM actions" (better name needed) for the things you can build: commands, autofixers, chat integration etc.

Note that CI is intentionally broken which is to be expected. The link checker is looking to validate `https://github.com/atomist/docs/edit/master/docs/glossary.md`, which refers to the "Edit on GitHub" link for the Glossary. Since I moved _glossary.md_ out of the `developer/`, the link checker is confused, as the file hasn't been moved out in the GitHub repo yet.

### CODE REVIEW

**Comment by jessitron** [comment]
build error is a known non-issue: https://github.com/atomist/docs-sdm/issues/15

**Comment by jessitron** [comment]
looking at it (http://docs-sdm.atomist.com.s3-website.us-west-2.amazonaws.com/ba19c50e586a6cefa31e4e5729f989df0507f7f8/developer/)
This is clearly so much better

The name "SDM actions" does need to change, that is not an technical term that we use. How about "What the SDM can do" ?
... and then the section needs a "Delivery" page that refers people to the section on goals.

**Comment by gjtorikian** [comment]
@jessitron I've added that now. 👍

**Comment by jessitron** [comment]
cool! I changed the tense, I haven't heard the plural used at all before.

**Comment by jessitron** [comment]
LGTM

**Review by philbeam — COMMENTED** [review]
Stop

**Comment by sksahalam786** [comment]
> [CLA assistant check](https://cla-assistant.io/atomist/docs?pullRequest=282)
> All committers have signed the CLA.

Google Assistant help me

**Comment by sksahalam786** [comment]
Inbox

**Comment by sksahalam786** [comment]
Dropbox

**Comment by sksahalam786** [comment]
Outbox

**Pull request merged**
