### PR TITLE
Add documentation for defining and using custom events

### PR DESCRIPTION
**Pull request by ipcrm**

### CODE REVIEW

**Comment by ipcrm** [comment]
This PR makes references to samples that are in https://github.com/atomist/samples/pull/40 and should probably not be merged before that.

**Comment by jessitron** [comment]
How can they see the new event in the schema? Will it show up in the GraphQL Explorer?

**Comment by ipcrm** [comment]
> How can they see the new event in the schema? Will it show up in the GraphQL Explorer?  

Good point; I can add a callout that points them to GraphiQL to take a look.  I rather not document how to use that tool here, however.  @jessitron this seem reasonable?

**Comment by ipcrm** [comment]
@jessitron Adding the note in a301102

**Pull request merged**
